services:
  mex-testing:
    build:
      context: .
    ports:
      - 8050:8050
    environment:
      - MEX_TESTING_HTTP_SERVER_HOST=0.0.0.0
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:8050/v0/_system/check" ]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - data:/app/data
volumes:
  data:
